/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HudLayout = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllHudCodes' : IDL.Func([], [IDL.Vec(HudLayout)], ['query']),
  'getHudCodeByName' : IDL.Func([IDL.Text], [HudLayout], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HudLayout = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllHudCodes' : IDL.Func([], [IDL.Vec(HudLayout)], ['query']),
    'getHudCodeByName' : IDL.Func([IDL.Text], [HudLayout], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };