/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HudLayout {
  'code' : string,
  'name' : string,
  'description' : string,
}
export interface Notice {
  'id' : bigint,
  'text' : string,
  'createdAt' : bigint,
}
export interface PdfChapter {
  'subject' : string,
  'pdfUrl' : string,
  'className' : string,
  'chapterName' : string,
}
export interface StudentRegistration {
  'studentName' : string,
  'subject' : string,
  'mobile' : string,
  'registeredAt' : bigint,
  'className' : string,
  'parentName' : string,
}
export interface _SERVICE {
  'addNotice' : ActorMethod<[string], bigint>,
  'addPdfChapter' : ActorMethod<[string, string, string, string], undefined>,
  'deleteNotice' : ActorMethod<[bigint], boolean>,
  'deletePdfChapter' : ActorMethod<[bigint], boolean>,
  'getAdminLastSeen' : ActorMethod<[], bigint>,
  'getAllChapters' : ActorMethod<[], Array<PdfChapter>>,
  'getAllHudCodes' : ActorMethod<[], Array<HudLayout>>,
  'getAllRegistrations' : ActorMethod<[], [Array<StudentRegistration>, bigint]>,
  'getChaptersBySubject' : ActorMethod<[string], Array<PdfChapter>>,
  'getChaptersBySubjectAndClass' : ActorMethod<
    [string, string],
    Array<PdfChapter>
  >,
  'getHudCodeByName' : ActorMethod<[string], HudLayout>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'registerStudent' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'setAdminLastSeen' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
