/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PdfChapter = IDL.Record({
  'subject' : IDL.Text,
  'pdfUrl' : IDL.Text,
  'className' : IDL.Text,
  'chapterName' : IDL.Text,
});
export const HudLayout = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const StudentRegistration = IDL.Record({
  'studentName' : IDL.Text,
  'subject' : IDL.Text,
  'mobile' : IDL.Text,
  'registeredAt' : IDL.Int,
  'className' : IDL.Text,
  'parentName' : IDL.Text,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const AttendanceRecord = IDL.Record({
  'studentName' : IDL.Text,
  'className' : IDL.Text,
  'rollNumber' : IDL.Text,
  'date' : IDL.Text,
  'markedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'addPdfChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'deletePdfChapter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAdminLastSeen' : IDL.Func([], [IDL.Int], ['query']),
  'getAllChapters' : IDL.Func([], [IDL.Vec(PdfChapter)], ['query']),
  'getAllHudCodes' : IDL.Func([], [IDL.Vec(HudLayout)], ['query']),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(StudentRegistration), IDL.Int], ['query']),
  'getChaptersBySubject' : IDL.Func([IDL.Text], [IDL.Vec(PdfChapter)], ['query']),
  'getChaptersBySubjectAndClass' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(PdfChapter)], ['query']),
  'getHudCodeByName' : IDL.Func([IDL.Text], [HudLayout], ['query']),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'setAdminLastSeen' : IDL.Func([], [], []),
  'setHeroPhoto' : IDL.Func([IDL.Text], [], []),
  'getHeroPhoto' : IDL.Func([], [IDL.Text], ['query']),
  'addNotice' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteNotice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getAttendanceByDate' : IDL.Func([IDL.Text], [IDL.Vec(AttendanceRecord)], ['query']),
  'getAttendanceByClassAndDate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(AttendanceRecord)], ['query']),
  'setAttendanceWindow' : IDL.Func([IDL.Bool], [], []),
  'getAttendanceWindowStatus' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PdfChapter = IDL.Record({
    'subject' : IDL.Text,
    'pdfUrl' : IDL.Text,
    'className' : IDL.Text,
    'chapterName' : IDL.Text,
  });
  const HudLayout = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const StudentRegistration = IDL.Record({
    'studentName' : IDL.Text,
    'subject' : IDL.Text,
    'mobile' : IDL.Text,
    'registeredAt' : IDL.Int,
    'className' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const AttendanceRecord = IDL.Record({
    'studentName' : IDL.Text,
    'className' : IDL.Text,
    'rollNumber' : IDL.Text,
    'date' : IDL.Text,
    'markedAt' : IDL.Int,
  });

  return IDL.Service({
    'addPdfChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'deletePdfChapter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAdminLastSeen' : IDL.Func([], [IDL.Int], ['query']),
    'getAllChapters' : IDL.Func([], [IDL.Vec(PdfChapter)], ['query']),
    'getAllHudCodes' : IDL.Func([], [IDL.Vec(HudLayout)], ['query']),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(StudentRegistration), IDL.Int], ['query']),
    'getChaptersBySubject' : IDL.Func([IDL.Text], [IDL.Vec(PdfChapter)], ['query']),
    'getChaptersBySubjectAndClass' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(PdfChapter)], ['query']),
    'getHudCodeByName' : IDL.Func([IDL.Text], [HudLayout], ['query']),
    'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'setAdminLastSeen' : IDL.Func([], [], []),
    'setHeroPhoto' : IDL.Func([IDL.Text], [], []),
    'getHeroPhoto' : IDL.Func([], [IDL.Text], ['query']),
    'addNotice' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteNotice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getAttendanceByDate' : IDL.Func([IDL.Text], [IDL.Vec(AttendanceRecord)], ['query']),
    'getAttendanceByClassAndDate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(AttendanceRecord)], ['query']),
    'setAttendanceWindow' : IDL.Func([IDL.Bool], [], []),
    'getAttendanceWindowStatus' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
